sudo: required

language: node_js

cache:
    directories:
      - node_modules

node_js:
  - "10"

services:
  - docker

install:
  - NODE_ENV=production npm ci

script:
  - echo 'Nothing to build'

after_success:
  - docker --version
  - docker build -f Dockerfile -t kybernetwork/sample-kyber-widget:$TRAVIS_COMMIT .

deploy:
  - provider: script
    script: bash .travis/docker_push
    on:
      all_branches: true
